INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.218:8080
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.218:8080
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:05:31] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:05:31] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:05:33] "[36mGET /static/js/bootstrap.min.js HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:05:33] "[36mGET /static/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:05:33] "[36mGET /static/img/navbar.png HTTP/1.1[0m" 304 -
ERROR:app:Exception on /add/Acer80088/5/46800.0 [POST]
Traceback (most recent call last):
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\OneDrive\Desktop\app1\ecommerce-website-flask\app.py", line 113, in addToCart
    sql_insert_data_query= "INSERT INTO CartItems VALUES ('{}','{}','{}','{}', curdate())".format(session['cart_id'],model_id,int(quantity),cost)
                                                                                                  ~~~~~~~^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\sessions.py", line 79, in __getitem__
    return super().__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'cart_id'
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:31:39] "[35m[1mPOST /add/Acer80088/5/46800.0 HTTP/1.1[0m" 500 -
ERROR:app:Exception on /add/Panasonic83050/2/391820.0 [POST]
Traceback (most recent call last):
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\OneDrive\Desktop\app1\ecommerce-website-flask\app.py", line 113, in addToCart
    sql_insert_data_query= "INSERT INTO CartItems VALUES ('{}','{}','{}','{}', curdate())".format(session['cart_id'],model_id,int(quantity),cost)
                                                                                                  ~~~~~~~^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\sessions.py", line 79, in __getitem__
    return super().__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'cart_id'
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:31:50] "[35m[1mPOST /add/Panasonic83050/2/391820.0 HTTP/1.1[0m" 500 -
ERROR:app:Exception on /add/Acer80088/5/46800.0 [POST]
Traceback (most recent call last):
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\OneDrive\Desktop\app1\ecommerce-website-flask\app.py", line 113, in addToCart
    sql_insert_data_query= "INSERT INTO CartItems VALUES ('{}','{}','{}','{}', curdate())".format(session['cart_id'],model_id,int(quantity),cost)
                                                                                                  ~~~~~~~^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\sessions.py", line 79, in __getitem__
    return super().__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'cart_id'
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:32:14] "[35m[1mPOST /add/Acer80088/5/46800.0 HTTP/1.1[0m" 500 -
ERROR:app:Exception on /add/Acer80088/2/46800.0 [POST]
Traceback (most recent call last):
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\OneDrive\Desktop\app1\ecommerce-website-flask\app.py", line 113, in addToCart
    sql_insert_data_query= "INSERT INTO CartItems VALUES ('{}','{}','{}','{}', curdate())".format(session['cart_id'],model_id,int(quantity),cost)
                                                                                                  ~~~~~~~^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\sessions.py", line 79, in __getitem__
    return super().__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'cart_id'
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:39:53] "[35m[1mPOST /add/Acer80088/2/46800.0 HTTP/1.1[0m" 500 -
ERROR:app:Exception on /add/Acer80088/5/46800.0 [POST]
Traceback (most recent call last):
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\OneDrive\Desktop\app1\ecommerce-website-flask\app.py", line 113, in addToCart
    sql_insert_data_query= "INSERT INTO CartItems VALUES ('{}','{}','{}','{}', curdate())".format(session['cart_id'],model_id,int(quantity),cost)
                                                                                                  ~~~~~~~^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\sessions.py", line 79, in __getitem__
    return super().__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'cart_id'
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:40:02] "[35m[1mPOST /add/Acer80088/5/46800.0 HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:40:26] "GET /product/Acer80088 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:40:26] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:40:26] "[36mGET /static/img/s5.png HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:40:26] "[36mGET /static/js/bootstrap.min.js HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:40:26] "[36mGET /static/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:40:26] "[36mGET /static/img/navbar.png HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:40:44] "GET /product/Acer80088 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:40:44] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:40:44] "[36mGET /static/img/s5.png HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:40:44] "[36mGET /static/js/bootstrap.min.js HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:42:18] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:42:19] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:42:19] "[36mGET /static/js/bootstrap.min.js HTTP/1.1[0m" 304 -
ERROR:app:Exception on /login [POST]
Traceback (most recent call last):
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\OneDrive\Desktop\app1\ecommerce-website-flask\app.py", line 203, in login
    if check_password_hash(user[1].decode(), password):
                           ^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:42:35] "[35m[1mPOST /login HTTP/1.1[0m" 500 -
ERROR:app:Exception on /login [POST]
Traceback (most recent call last):
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\OneDrive\Desktop\app1\ecommerce-website-flask\app.py", line 203, in login
    if check_password_hash(user[1].decode(), password):
                           ^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:46:47] "[35m[1mPOST /login HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.218:8080
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:47:47] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:47:47] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:47:47] "[36mGET /static/js/bootstrap.min.js HTTP/1.1[0m" 304 -
ERROR:app:Exception on /login [POST]
Traceback (most recent call last):
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\OneDrive\Desktop\app1\ecommerce-website-flask\app.py", line 203, in login
    if check_password_hash(user[1].decode(), password):
                           ^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:48:09] "[35m[1mPOST /login HTTP/1.1[0m" 500 -
ERROR:app:Exception on /login [POST]
Traceback (most recent call last):
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\OneDrive\Desktop\app1\ecommerce-website-flask\app.py", line 203, in login
    if check_password_hash(user[1].decode(), password):
                           ^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:48:14] "[35m[1mPOST /login HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:48:18] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:48:18] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [23/Nov/2023 17:48:18] "[36mGET /static/js/bootstrap.min.js HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [24/Nov/2023 00:14:05] "GET /product/Toshiba35158 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Nov/2023 00:14:05] "[36mGET /static/img/s5.png HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [24/Nov/2023 00:14:05] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [24/Nov/2023 00:14:05] "[36mGET /static/js/bootstrap.min.js HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [24/Nov/2023 00:14:06] "[36mGET /static/img/navbar.png HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [24/Nov/2023 00:14:06] "[36mGET /static/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1[0m" 304 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.218:8080
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.218:8080
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [24/Nov/2023 14:27:48] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Nov/2023 14:27:48] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [24/Nov/2023 14:27:48] "[36mGET /static/img/navbar.png HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [24/Nov/2023 14:27:48] "[36mGET /static/js/bootstrap.min.js HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [24/Nov/2023 14:27:48] "[36mGET /static/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [24/Nov/2023 14:27:49] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [24/Nov/2023 14:27:56] "GET /registration HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Nov/2023 14:27:56] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [24/Nov/2023 14:27:56] "[36mGET /static/js/bootstrap.min.js HTTP/1.1[0m" 304 -
ERROR:app:Exception on /registration [POST]
Traceback (most recent call last):
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhuvanesh\OneDrive\Desktop\app1\ecommerce-website-flask\app.py", line 127, in registration
    with get_database_connection() as connection:
         ^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'get_database_connection' is not defined
INFO:werkzeug:127.0.0.1 - - [24/Nov/2023 14:28:09] "[35m[1mPOST /registration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [24/Nov/2023 14:28:23] "POST /registration HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Nov/2023 14:28:23] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [24/Nov/2023 14:28:23] "[36mGET /static/js/bootstrap.min.js HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [24/Nov/2023 14:28:35] "POST /registration HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Nov/2023 14:28:35] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [24/Nov/2023 14:28:35] "[36mGET /static/js/bootstrap.min.js HTTP/1.1[0m" 304 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.218:8080
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.218:8080
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.218:8080
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:192.168.29.218 - - [24/Nov/2023 14:44:51] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.29.218 - - [24/Nov/2023 14:44:51] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:192.168.29.218 - - [24/Nov/2023 14:44:51] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 -
INFO:werkzeug:192.168.29.218 - - [24/Nov/2023 14:44:51] "GET /static/img/navbar.png HTTP/1.1" 200 -
INFO:werkzeug:192.168.29.218 - - [24/Nov/2023 14:44:51] "GET /static/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 -
INFO:werkzeug:192.168.29.218 - - [24/Nov/2023 14:44:53] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.29.218 - - [24/Nov/2023 14:44:55] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.29.218 - - [24/Nov/2023 14:44:55] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.29.218 - - [24/Nov/2023 14:44:55] "[36mGET /static/js/bootstrap.min.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.29.218 - - [24/Nov/2023 14:44:57] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.29.218 - - [24/Nov/2023 14:44:57] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.29.218 - - [24/Nov/2023 14:44:57] "[36mGET /static/js/bootstrap.min.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.29.218 - - [24/Nov/2023 14:45:02] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.29.218 - - [24/Nov/2023 14:45:02] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.29.218 - - [24/Nov/2023 14:45:02] "[36mGET /static/js/bootstrap.min.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.29.218 - - [24/Nov/2023 14:45:07] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.29.218 - - [24/Nov/2023 14:45:07] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.29.218 - - [24/Nov/2023 14:45:07] "[36mGET /static/js/bootstrap.min.js HTTP/1.1[0m" 304 -